services:
  - type: web
    name: finance-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn finance_app.wsgi:application
    pythonVersion: 3.10.13  # ğŸ‘ˆğŸ½ Use a stable Python version
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: finance_tracker.settings
      - key: PYTHON_VERSION
        value: 3.10.13
